assignment/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from guestbook import urls as guestbook_urls

urlpatterns = [
    url(r'^', include(guestbook_urls)),
    url(r'^admin/', include(admin.site.urls)),
]

assignment1/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = (
    url(r'^', include('guestbook.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

guestbook/urls.py
from django.conf.urls import include, url
from django.contrib import admin


from records import urls as record_urls
urlpatterns = [
    url(r'^', include(record_urls)),
    url(r'^admin/', include(admin.site.urls)),
]

records/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.RecordRedirectView.as_view(), name='records-root'),
    url(r'^records/$', views.RecordCreateView.as_view(), name='record-list'),
    url(r'^records/(?P<pk>\d+)/$', views.RecordDetailView.as_view(), name='record-detail'),
    url(r'^thanks/$',views.RecordThanksView.as_view(), name='thank-you'),  
]

guestbook/comments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone
from math import trunc

# Create your models here.

def calc_long_ago(created_at):
    delta = timezone.now() - created_at
    print(created_at, timezone.now(), delta.seconds)
    if delta.days > 15:
        return "a while ago"
    else:
        if delta.days > 1:
            t = trunc(delta.days)
            return "{:d} day{} ago".format(t, "" if t > 1 else "s")
        else:
            if delta.seconds > 3600:
                t = trunc(delta.seconds/60/60)
                return "{:d} hours ago".format(t, "" if t > 1 else "s")

            elif delta.seconds > 300:
                t = trunc(delta.seconds/60)
                return "{:d} minute{} ago".format(t, "" if t > 1 else "s")
            else:
                return "just now"

class Comment(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=200)
    text = models.CharField(max_length=1024)
    created_at = models.DateTimeField(default=timezone.now)
    is_public = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    def long_ago(self):
        return calc_long_ago(self.created_at)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return '<{}> {}'.format(self.author, self.title)

    def get_absolute_url(self):
        return reverse('comments_detail', kwargs={'pk': self.pk})


class Message(models.Model):
    text = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    comment = models.ForeignKey('Comment')
    created_at = models.DateTimeField(default=timezone.now)
    is_public = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    is_spam = models.BooleanField(default=False)

    def long_ago(self):
        return calc_long_ago(self.created_at)


    def __str__(self):
        return '<{}> {}'.format(self.user, self.text)

guestbook/comments/forms.py
from django import forms

from .models import Comment, Message

class CreateCommentForm(forms.ModelForm):
    text = forms.CharField(
        label="Comment",
        max_length=1024,
        widget=forms.Textarea)

    class Meta:
        model = Comment
        fields = ('title', 'text', 'is_public')

class AddMessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ('text',)

guestbook/comments/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from django.views.generic import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.utils import timezone

from .models import Comment, Message
from .forms import AddMessageForm, CreateCommentForm


class AllCommentList(SuccessMessageMixin, CreateView):
    model = Comment
    template_name = 'public_comments_list.html'
    form_class = AddMessageForm
    context_object_name = 'comments'
    success_message = "Message was created successfully"

    def form_valid(self, form):
        comment_id = self.request.POST['comment_id']
        form.instance.user = self.request.user
        form.instance.comment = Comment.objects.get(pk=comment_id)
        return super(AllCommentList, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(AllCommentList, self).get_context_data(**kwargs)
        context['comments'] = self.model.objects.filter(is_active=True).filter(is_public=True)

        return context

    def get_success_url(self):
        return reverse_lazy('all_comments_list')


class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

class UserCommentList(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'comments_list.html'
    form_class = CreateCommentForm
    context_object_name = 'comments'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(UserCommentList, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('user_comments_list')

    def get_context_data(self, **kwargs):
        context = super(UserCommentList, self).get_context_data(**kwargs)
        context['comments'] = self.model.objects.filter(is_active=True).filter(author=self.request.user.pk)
        return context


class UserCommentDetail(LoginRequiredMixin, DetailView):
    model = Comment
    template_name = 'comments_detail.html'

class UserCommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'comments_form.html'
    form_class = CreateCommentForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(UserCommentCreate, self).form_valid(form)

class UserCommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    template_name = 'comments_form.html'
    success_url = reverse_lazy('user_comments_list')
    fields = ['title', 'text', 'created_at', 'is_public', 'is_active']

    ## Todo - makesure user is author

class UserCommentDelete(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'comments_confirm_delete.html'
    success_url = reverse_lazy('user_comments_list')

    ## Todo - change delete to update 'is_active' to False

    ## Todo - makesure user is author

guestbook/comments/templates/comments_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object.title }}?</p>
    <button type="submit">
      Yes
    </button>
    <a href="{% url 'user_comments_list' %}">no</a>
</form>

{% endblock %}

guestbook/comments/templates/comments_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ object.title }}</h2>
<p><em>by {{ object.author.username }}</em></p>
<p>{{ object.text }}</p>

<a href="{% url 'comments_edit' object.pk %}">Edit</a>
|
<a href="{% url 'comments_delete' object.pk %}">Delete</a>
{% endblock %}

guestbook/comments/templates/comments_form.html
{% extends "base.html" %}

{% block content %}
    {% if object %}
        <h2>Edit {{ object.title }}</h2>
    {% else %}
        <h2>Create</h2>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
          <button type="submit">
            Submit
          </button>
        </p>
    </form>
{% endblock %}

guestbook/comments/templates/comments_list.html
{% extends "base.html" %}

{% block content %}

    <hr>
    <div class="large-12 columns">

        <h3>Hi {{user}}, here are your posts</h3><a href="#" class="button round small info" data-reveal-id="CreateComment">Click here to create new Comment</a>
        <hr>
        {% for comment in comments %}
            <div class="row">
                <div class="large-2 columns small-3">
                    <img src="http://placehold.it/80x80&text=[img]"/>
                    <p>TODO - Make public: </p>
                    <div class="switch round small">
                        <input id="exampleRadioSwitch3" type="checkbox" checked name="testGroup">
                        <label for="exampleRadioSwitch3">TODO - Make public</label>
                    </div>
                </div>
                <div class="large-10 columns">
                    <ul class="breadcrumbs">
                        <li>your post was created {{ comment.long_ago }}.</li>
                        <li><a href="{% url 'comments_edit' comment.pk %}">edit</a></li>
                        <li><a href="{% url 'comments_delete' comment.pk %}">delete</a></li>
                    </ul>
                    {{ comment.text }}
                    <hr>
                    <p><strong>
                    {% if comment.message_set.count > 0 %}
                        {{ comment.message_set.count }} message{{ comment.message_set.count|pluralize }} left.
                    {% else %}
                        No messages left yet.
                    {% endif %}
                    </strong>
                    </p>

                    {% for message in comment.message_set.all %}
                    <div class="row">
                        <div class="small-11 small-centered columns">
                           <ul class="breadcrumbs">
                               <li><strong>{{ message.user }}</strong> &nbsp;&nbsp;&nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;&nbsp; message sent {{ message.long_ago }}.</li>
                           </ul>
                           <p>{{ message.text }}</p>
                       </div>
                   </div>
                   {% endfor %}
                   {% if not user.is_anonymous %}
                        <a href="" class="button round small info" data-reveal-id="AddMessage" onclick="javascript:setid({{comment.pk}}); return false;">Add Message</a>
                    {% endif %}
                </div>
            </div>
            <hr>
        {% endfor %}

    <div id="CreateComment" class=reveal-modal data-reveal aria-labelledby="Create New Comment" aria-hidden="true" role="dialog">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p>
              <button type="submit">
                Submit
              </button>
            </p>
        </form>
        <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>

{% endblock %}

guestbook/comments/templates/index.html
{% extends "base.html" %}

{% block content %}

    <h2>Welcome to Guestbook</h2>

{% endblock content %}

guestbook/comments/templates/public_comments_list.html
{% extends "base.html" %}

{% block content %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <hr>
    <div class="large-12 columns">

        {% if user.is_anonymous %}
            <h3>Hi there, please register or login to add messages</h3>
        {% else %}
            <h3>Hi {{user}}, feel free to add messages</h3>
        {% endif %}

        <hr>
        {% for comment in comments %}
            <div class="row">
                <div class="large-2 columns small-3">
                    <img src="http://placehold.it/80x80&text=[img]"/>
                </div>
                <div class="large-10 columns">
                    <ul class="breadcrumbs">
                        <li><strong>{{ comment.author }}</strong> &nbsp;&nbsp;&nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;&nbsp; post created {{ comment.long_ago }}.</li>
                    </ul>
                    {{ comment.text }}
                    <hr>
                    <p><strong>
                    {% if comment.message_set.count > 0 %}
                        {{ comment.message_set.count }} message{{ comment.message_set.count|pluralize }} left.
                    {% else %}
                        No messages left yet.
                    {% endif %}
                    </strong>
                    </p>

                    {% for message in comment.message_set.all %}
                   <div class="row">
                       <div class="small-11 small-centered columns">
                           <ul class="breadcrumbs">
                               <li><strong>{{ message.user }}</strong> &nbsp;&nbsp;&nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;&nbsp; message sent {{ message.long_ago }}.</li>
                           </ul>
                           <p>{{ message.text }}</p>
                       </div>
                   </div>
                   {% endfor %}
                   {% if not user.is_anonymous %}
                        <a href="" class="button round small info" data-reveal-id="AddMessage" onclick="javascript:setid({{comment.pk}}); return false;">Add Message</a>
                    {% endif %}
                </div>
            </div>
            <hr>
        {% endfor %}
    {% if not user.is_anonymous %}
        <div id="AddMessage" class=reveal-modal data-reveal aria-labelledby="Create New Message" aria-hidden="true" role="dialog">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" name="comment_id" id="comment_id" />
                <p>
                  <button type="submit">
                    Submit
                  </button>
                </p>
            </form>
            <a class="close-reveal-modal" aria-label="Close">&#215;</a>
        </div>
    {% endif %}
{% endblock %}